export const robots = [
  {
    id:1,
    name:"Amit Shah",
    username:"amitshah147",
    email:"amitshah147@gmail.com"
  },
  {
    id:2,
    name:"kiran",
    username:"kittu2108",
    email:"kiran@gmail.com"
  },
  {
    id:3,
    name:"warner",
    username:"warner335",
    email:"warner@gmail.com"
  },
  {
    id:4,
    name:"rohit",
    username:"hitman264",
    email:"rohit264@gmail.com"
  },
  {
    id:5,
    name:"arjun",
    username:"allu26",
    email:"allu26@gmail.com"
  },
  {
    id:6,
    name:"Dhoni",
    username:"dhoni007",
    email:"dhoni007@gmail.com"
  }
]
